# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Delirium Detector' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Delirium Detector

  target 'Delirium DetectorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Delirium DetectorUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod ‘Firebase’
  pod ‘FirebaseAuth’
  pod ‘FirebaseDatabase’
  pod ‘GoogleSignIn’
	
end
